services:
  postgres:
    image: postgres:16
    container_name: monorepo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mayur@123
      POSTGRES_DB: template1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d template1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: monorepo-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:Mayur%40123@postgres:5432/template1?schema=public
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        DATABASE_URL: postgresql://postgres:Mayur%40123@postgres:5432/template1?schema=public
    container_name: monorepo-web
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:Mayur%40123@postgres:5432/template1?schema=public
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    container_name: monorepo-websocket
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:Mayur%40123@postgres:5432/template1?schema=public
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: